# Site settings
title: RoscaS
name: RoscaS # your name
email: sol.rosca@gmail.com # your email address
description: >
    Just some notes. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://roscas.github.io" # the base hostname & protocol for your site
# twitter_username:  # your Twitter username
github_username: RoscaS # your Github username
# disqus_username:  # your disqus username

google-analytics: UA-99742998-1 # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown


